export const usinaConsorcioMap: { [key: string]: string } = {
  'PEQUERI I': 'Cemig (GSM Solarion)',
  'CORONEL ABÍLIO': 'Cemig (GSM Solarion)',
  'OLARIA CX1': 'Cemig (GSM Solarion)',
  'OLARIA CX2': 'Cemig (GSM Solarion)',
  'TRIUNFO CX1': 'Cemig (GSM Solarion)',
  'TRIUNFO CX2': 'Cemig (GSM Solarion)',
  'LOTE 14': 'Cemig (GSM Solarion)',
  'CAMPO BELO I': 'Cemig (GSM Solarion)',
  'CAMPO BELO II': 'Cemig (Consórcio Prime 01)',
  'LOTE 12': 'Cemig (Consórcio Prime 01)',
  'LOTE 14A': 'Cemig (Consórcio Prime 01)',
  'BELMIRO BRAGA I': 'Cemig (Consórcio Prime 01)',
  'TRIUNFO III': 'Cemig (Consórcio Prime 01)',
  'CAMPO ALEGRE II': 'Light (Consórcio Prime 02)',
  'CAMPO ALEGRE III': 'Light (Consórcio Prime 02)',
  'VARGEM LINDA I': 'Light (Consórcio Prime 02)',
  'VARGEM LINDA II': 'Light (Consórcio Prime 02)',
  'VARGEM LINDA III': 'Light (Consórcio Prime 02)',
  'SÃO JOSÉ I': 'Light (Consórcio Prime 02)',
  'SÃO JOSÉ II': 'Light (Consórcio Prime 02)',
  'SÃO JOSÉ III': 'Light (Consórcio Prime 02)',
  'SÃO FRANCISCO I': 'Light (Consórcio Prime 02)',
  'SANTA LUIZA I': 'Light (Consórcio Prime 02)',
  'SANTA CECÍLIA I': 'Light (Consórcio Prime 02)',
  'SANTA CECÍLIA II': 'Light (Consórcio Prime 02)',
  'SANTA CECÍLIA III': 'Light (Consórcio Prime 02)',
  'SÃO FRANCISCO II': 'ENEL (Consorcio Prime 03)',
  'RIO BONITO I': 'ENEL (Consorcio Prime 03)',
};
